-- Activity определение

CREATE TABLE IF NOT EXISTS Activity (
	ID INTEGER NOT NULL,
	NAME TEXT(100) NOT NULL,
	USER_ID INTEGER NOT NULL,
	TYPE_ID INTEGER NOT NULL,
	Duration TEXT(50) NOT NULL,
	START_TIME TEXT(50) NOT NULL,
	END_TIME TEXT(50) NOT NULL,
	DESCRIPTION TEXT(2000),
	CONSTRAINT Activities_PK PRIMARY KEY (ID)
	FOREIGN KEY (Type_ID) REFERENCES Activity_Types(ID)
	FOREIGN KEY (User_ID) REFERENCES Users(ID)
);

-- Users определение

CREATE TABLE IF NOT EXISTS  Users (
	ID INTEGER NOT NULL,
	USERNAME TEXT(100) NOT NULL,
	EMAIL TEXT(50) NOT NULL,
	PASSWORD TEXT(100) NOT NULL,
	CONSTRAINT Users_PK PRIMARY KEY (ID)
);

-- Activity_Types определение

CREATE TABLE IF NOT EXISTS  "Activity_Types" (
	ID INTEGER NOT NULL,
	NAME TEXT(50) NOT NULL,
	ICON_NAME TEXT(200) NOT NULL,
	CONSTRAINT Activity_Type_PK PRIMARY KEY (ID)
);

INSERT OR IGNORE INTO "Activity_Types" (ID, NAME, ICON_NAME)
VALUES (1, 'Sport', 'SportLink');

INSERT OR IGNORE INTO "Activity_Types" (ID, NAME, ICON_NAME)
VALUES (2, 'Health', 'HealthLink');

INSERT OR IGNORE INTO "Activity_Types" (ID, NAME, ICON_NAME)
VALUES (3, 'Sleep', 'SleepLink');

INSERT OR IGNORE INTO "Activity_Types" (ID, NAME, ICON_NAME)
VALUES (4, 'Study', 'StudyLink');

INSERT OR IGNORE INTO "Activity_Types" (ID, NAME, ICON_NAME)
VALUES (5, 'Rest', 'RestLink');

INSERT OR IGNORE INTO "Activity_Types" (ID, NAME, ICON_NAME)
VALUES (6, 'Eat', 'SportLink');

INSERT OR IGNORE INTO "Activity_Types" (ID, NAME, ICON_NAME)
VALUES (7, 'Coding', 'CodingLink');

INSERT OR IGNORE INTO "Activity_Types" (ID, NAME, ICON_NAME)
VALUES (8, 'Other', 'OtherLink');
